energy/api/urls.py
from django.contrib import admin
from django.urls import path
from energy.api.views import api_sockets_view, api_find_new_sockets, api_socket_status, api_update_sockets

app_name = 'api'

urlpatterns = [
    path('', api_sockets_view, name='api-root'),
    path('sockets', api_sockets_view, name='api-sockets'),
    path('sockets/update', api_update_sockets, name='api-sockets-update'),
    path('sockets/new', api_find_new_sockets, name='api-sockets-new'),
    path('sockets/status/<int:id>/<str:status>', api_socket_status, name='api-socket-status-update'),
]

energy/sockets/urls.py
from django.contrib import admin
from django.urls import path, include
from energy.sockets.views import sockets_view, find_new_sockets, update_sockets, SocketsUpdateView, change_status

app_name = 'sockets'

urlpatterns = [
    path('', sockets_view, name='sockets'),
    path('new', find_new_sockets, name='sockets-new'),
    path('status_update', update_sockets, name='socket-status-update'),
    path('update/<int:pk>/', SocketsUpdateView.as_view(), name='sockets-update'),
    path('change-status/<int:id>/<str:status>', change_status, name='socket-status-change'),
]

energy/urls.py
from django.contrib import admin
from django.urls import path, include
from energy.sockets.views import sockets_view

app_name = 'energy'

urlpatterns = [
    path('', sockets_view),
    path('admin/', admin.site.urls),
    path('sockets/', include('energy.sockets.urls')),
    path('api/', include('energy.api.urls')),
]

energy/api/models.py
from django.db import models

# Create your models here.

energy/core/models.py
from django.db import models

# Create your models here.

energy/sockets/models.py
from django.db import models
# Create your models here.

class Sockets(models.Model):
    network_name = models.CharField(max_length=100, unique=True)
    friendly_name = models.CharField(max_length=100, blank=True, null=True)
    type = models.CharField(max_length=100, blank=True, null=True)
    power_on = models.BooleanField(default=False)
    switch_lock = models.BooleanField(default=False)
    serial = models.CharField(max_length=100, blank=True, null=True)
    ip = models.GenericIPAddressField(protocol='IPv4', blank=True, null=True)

    def __str__(self):
        return self.friendly_name

    def turn_on(self):
        """
        Set power_on to True, signal update_socket_status() will be called
        to turn on socket via the API
        """
        self.power_on = True
        self.save()

    def turn_off(self):
        """
        Set power_on to False, signal update_socket_status() will be called
        to turn off socket via the API
        """
        self.power_on = False
        self.save()
    
    class Meta:
        verbose_name_plural = 'Sockets'

energy/sockets/forms.py
# Create django forms for the sockets app
from django import forms
from .models import Sockets

# Create django forms for the sockets app
class SocketsForm(forms.ModelForm):
    class Meta:
        model = Sockets
        fields = ('network_name', 'friendly_name', 'type', 'power_on', 'switch_lock', 'serial', 'ip')
        widgets = {
            'network_name': forms.TextInput(attrs={'class': 'form-control','readonly': True}),
            'friendly_name': forms.TextInput(attrs={'class': 'form-control'}),
            'type': forms.TextInput(attrs={'class': 'form-control','readonly': True}),
            'power_on': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'switch_lock': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'serial': forms.TextInput(attrs={'class': 'form-control','readonly': True}),
            'ip': forms.TextInput(attrs={'class': 'form-control','readonly': True}),
        }

energy/api/views.py
from django.http import JsonResponse
from energy.sockets.models import Sockets
import json 
from energy.tasks import find_new_sockets_task, update_socket_status_task, update_sockets_task

def api_sockets_view(request):
    """
    API endpoint that shows all sockets information
    """
    data = Sockets.objects.filter(type='HWE-SKT').values()
    return JsonResponse(list(data), safe=False)

def api_find_new_sockets(request):
    """
    API endpoint that refreshes all sockets information
    """
    try:
        find_new_sockets_task.delay()
        return JsonResponse({'status': 'ok'}, safe=False)
    except:
        return JsonResponse({'status': 'error', 'message': 'Error refreshing sockets'}, safe=False)

def api_update_sockets(request):
    """
    API endpoint that refreshes all sockets information
    """
    try:
        update_sockets_task.delay()
        return JsonResponse({'status': 'ok'}, safe=False)
    except:
        return JsonResponse({'status': 'error', 'message': 'Error refreshing sockets'}, safe=False)

def api_socket_status(request, id, status):
    """
    API endpoint that enables to change the power_on status of a socket
    """
    socket = Sockets.objects.get(pk=id)
    if isinstance(socket, Sockets):
        if status == 'on':
            socket.power_on = True
            socket.save()
            update_socket_status_task.delay(socket.id, 'on')
            return JsonResponse({'status': 'ok'}, safe=False)
        elif status == 'off':
            socket.power_on = False
            socket.save()
            update_socket_status_task.delay(socket.id, 'off')
            return JsonResponse({'status': 'ok'}, safe=False)
        else:
            return JsonResponse({'status': 'failed', 'error': 'Socket not found'})
        
    return JsonResponse({'status': 'failed', 'error': 'Socket not found'})

energy/core/views.py
from django.shortcuts import render

# Create your views here.

energy/sockets/views.py
from django.shortcuts import render
from energy.sockets.forms import SocketsForm
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from energy.sockets.models import Sockets
from django.core.management import call_command
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy
from django.core import serializers
from energy.tasks import find_new_sockets_task, update_socket_status_task, update_sockets_task
import json

def sockets_view(request):
    sockets = Sockets.objects.all()
    context = {'sockets': sockets}
    return render(request, 'sockets/sockets_list.html', context)

class SocketsUpdateView(UpdateView):
    model = Sockets
    form_class = SocketsForm
    template_name = 'sockets/sockets_form.html'
    success_url = reverse_lazy('sockets:sockets')

def update_sockets(request):
    try:
        update_sockets_task.delay()
        return redirect('sockets:sockets')
    except Exception as e:
        return JsonResponse({'status': 'failed', 'error': f'Failed updating sockets with error: {e}'})


def find_new_sockets(self):
    try:
        find_new_sockets_task.delay()
        return redirect('sockets:sockets')
    except:
        return redirect('sockets:sockets')

def change_status(request, id, status):
    """
    Change the power_on status of a socket, after save the signal will be
    called to turn on/off the socket 
    """
    socket = Sockets.objects.get(pk=id)
    if isinstance(socket, Sockets):
        if status == 'on':
            socket.power_on = True
            update_socket_status_task.delay(socket.id, 'on')
        elif status == 'off':
            socket.power_on = False
            update_socket_status_task.delay(socket.id, 'off')
        else:
            return redirect('sockets:sockets')
        socket.save()
    else:
        return JsonResponse({'status': 'failed', 'error': 'Socket not found'})
        #return json.dumps({'status': 'failed', 'error': 'Socket not found'})

    return redirect('sockets:sockets')

energy/core/templates/core/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Homewizard Energy Socket Manager</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  </head>
  <body>
    {% block content %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    


    <script>
      const refreshSocketsApi = async () => {
        const response = await fetch('{% url "api:api-sockets-new" %}');
        const myJson = await response.json(); 
      }

      const updateSocketsApi = async () => {
        const response = await fetch('{% url "api:api-sockets-update" %}');
        const myJson = await response.json(); 
      }

      var refreshModal = document.getElementById('refreshModal');
      refreshModal.addEventListener('shown.bs.modal', function (event) {
        let totalSeconds = 15;
        refreshSocketsApi();
        var x = setInterval(function() {
          document.getElementById("refresh-timer").innerHTML = totalSeconds;
          totalSeconds--;

          if (totalSeconds === 10) {
            updateSocketsApi();
          }

          if (totalSeconds === 0) {
            window.location.reload();
          }
        }, 1000);

      })
    </script>    
  
  </body>
</html>

energy/sockets/templates/sockets/sockets_form.html
{% extends "core/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h1>Homewizard Energy Sockets</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <form class="my-class" method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input class="btn btn-success" type="submit" value="Update">
                </form>  
            </div>
{% endblock %}

energy/sockets/templates/sockets/sockets_list.html
{% extends "core/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h1>Homewizard Energy Sockets</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-12 mt-5">
            </div>
        </div>
        <div class="row">
            <div class="col-11">
                
                    <table class="table mb-4">
                        <thead>
                            <tr>
                                <th scope="col">Network name</th>
                                <th scope="col">Friendly name</th>
                                <th scope="col">Type</th>
                                <th scope="col">Serial</th>
                                <th scope="col">IP</th>
                                <th scope="col">Status</th>
                                <th scope="col">Edit</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for socket in sockets %}
                            {% if socket.type == 'HWE-SKT' %}
                            <tr>
                                <td><p>{{ socket.network_name }}</p></td>
                                <td><p>{{ socket.friendly_name }}</p></td>
                                <td><p>{{ socket.type }}</p></td>
                                <td><p>{{ socket.serial }}</p></td>
                                <td><p>{{ socket.ip }}</p></td>
                                <td>{% if socket.power_on == True %}<a href="{% url 'sockets:socket-status-change' id=socket.pk status='off' %}"><button class="btn btn-danger">Turn off</button></a>{% else %}<a href="{% url 'sockets:socket-status-change' id=socket.pk status='on' %}"><button class="btn btn-success">Turn On</button></a>{% endif %}</td>
                                <td><a href="{% url 'sockets:sockets-update' pk=socket.pk %}"><button class="btn btn-primary">Edit</button></a></td>
                            </tr>
                            {% endif %}
                            {% endfor %}
                        <tbody>
                    </table>
                
            </div>
            <div class="col-1">
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <a href="#"><button id="modalButton" data-bs-toggle="modal" data-bs-target="#refreshModal" class="btn btn-primary">Refresh sockets</button></a>
            </div>
    </div>

    <!-- Refresh Modal HTML -->
    <div id="refreshModal" class="modal fade" tabindex="-1">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header text-center">
                    <h5 class="modal-title text-center">Refreshing Energy Sockets</h5>
                </div>
                <div class="modal-body">
                    <p class="fs-2 text-center" id="refresh-timer">15</p>
                </div>
            </div>
        </div>
        </div>
{% endblock %}